const authors = `<names variable="author"><name initialize-with=". " and="text" delimiter=", "/><substitute><names variable="editor"/><text variable="title"/></substitute></names>`;
const bibliography = `<layout suffix="."><group delimiter=". "><text macro="authors"/><text variable="title"/><group delimiter=" "><text variable="container-title" font-style="italic"/><group delimiter=";"><date variable="issued"><date-part name="year"/></date><group delimiter=":"><group><text variable="volume"/><text variable="issue" prefix="(" suffix=")"/></group><text variable="page"/></group></group></group><text variable="publisher"/><text variable="DOI" prefix="doi: "/></group></layout>`;
const prefix = `<style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" class="in-text"><info><title>Markedown Academic</title><id>https://markedown.local/styles/academic</id><updated>2026-09-07T00:00:00Z</updated></info><macro name="authors">${authors}</macro><macro name="short-author"><names variable="author"><name form="short" and="text"/><substitute><text variable="title" form="short"/></substitute></names></macro>`;
export const citationStyles = {
  numeric: `${prefix}<citation collapse="citation-number"><sort><key variable="citation-number"/></sort><layout prefix="[" suffix="]" delimiter=", "><text variable="citation-number"/></layout></citation><bibliography et-al-min="7" et-al-use-first="6" second-field-align="flush"><layout suffix="."><text variable="citation-number" suffix=". "/><group delimiter=". "><text macro="authors"/><text variable="title"/><group delimiter=" "><text variable="container-title" font-style="italic"/><group delimiter=";"><date variable="issued"><date-part name="year"/></date><group delimiter=":"><group><text variable="volume"/><text variable="issue" prefix="(" suffix=")"/></group><text variable="page"/></group></group></group><text variable="publisher"/><text variable="DOI" prefix="doi: "/></group></layout></bibliography></style>`,
  'author-date': `${prefix}<citation et-al-min="3" et-al-use-first="1" disambiguate-add-year-suffix="true"><sort><key macro="short-author"/><key variable="issued"/></sort><layout prefix="(" suffix=")" delimiter="; "><group delimiter=", "><text macro="short-author"/><date variable="issued"><date-part name="year"/></date></group></layout></citation><bibliography hanging-indent="true" et-al-min="7" et-al-use-first="6"><sort><key macro="authors"/><key variable="issued"/><key variable="title"/></sort>${bibliography}</bibliography></style>`,
} as const;

export const citationLocale = `<locale xmlns="http://purl.org/net/xbiblio/csl" xml:lang="en-US" version="1.0"><terms><term name="and">and</term><term name="et-al">et al.</term><term name="no date">n.d.</term><term name="page-range-delimiter">–</term><term name="citation-range-delimiter">–</term><term name="open-quote">“</term><term name="close-quote">”</term><term name="open-inner-quote">‘</term><term name="close-inner-quote">’</term><term name="reference" form="short"><single>ref.</single><multiple>refs.</multiple></term><term name="page" form="short"><single>p.</single><multiple>pp.</multiple></term><term name="editor" form="short"><single>ed.</single><multiple>eds.</multiple></term></terms></locale>`;
