import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowDown, ArrowUp, FolderOpen, Minus, Plus, RotateCcw, Search, X } from 'lucide-react';
import { defaultExportPresets, tableStyleNames, themeLabels, themeNames, type ExportFormat, type RuntimePlatform, type Settings, type SettingsAction } from '../shared/contracts';
import './preferences.css';
import WordPreferences from './WordPreferences';
import CitationCredits from './CitationCredits';
import { diagramEngineAvailable } from '../shared/markdown-diagrams';

interface Props { settings: Settings; zh: boolean; version: string; platform: RuntimePlatform; arch: string; pandoc: string | null | undefined; update(patch: Partial<Settings>): Promise<void>; documentPrefix?: string; updateDocumentPrefix?(prefix: string): void; close(): void; error(message: string): void; disableWritingModes(): void; initialCategory?: Category; initialQuery?: string }
type Category = 'file' | 'editor' | 'image' | 'markdown' | 'export' | 'appearance' | 'general';
type BooleanKey = { [K in keyof Settings]: Settings[K] extends boolean ? K : never }[keyof Settings];
const shortcutCommands = [['new','新建','New','Ctrl+N'],['open','打开','Open','Ctrl+O'],['save','保存','Save','Ctrl+S'],['saveAs','另存为','Save as','Ctrl+Shift+S'],['find','查找','Find','Ctrl+F'],['replace','替换','Replace','Ctrl+H'],['settings','偏好设置','Preferences','Ctrl+,'],['mode','源码模式','Source mode','Ctrl+/'],['focusMode','专注模式','Focus mode','F8'],['typewriter','打字机模式','Typewriter mode','F9']];
export default function Preferences({ settings: s, zh, version, platform, arch, pandoc, update, documentPrefix, updateDocumentPrefix, close, error, disableWritingModes, initialCategory = 'file', initialQuery = '' }: Props) {
  const [category, setCategory] = useState<Category>(initialCategory); const [query, setQuery] = useState(initialQuery); const [preset, setPreset] = useState('general');
  const [message, setMessage] = useState(''); const [shortcuts, setShortcuts] = useState(false); const ref = useRef<HTMLElement>(null);
  const t = (cn: string, en: string) => zh ? cn : en;
  const platformName = platform === 'win32' ? 'Windows' : platform === 'linux' ? 'Linux' : platform === 'darwin' ? 'macOS' : platform;
  const lineEndingOptions: Array<[Settings['defaultLineEnding'], string]> = platform === 'win32' ? [['CRLF','Windows (CRLF)'],['LF','Unix (LF)']] : [['LF','Unix (LF)'],['CRLF','Windows (CRLF)']];
  useEffect(() => { setCategory(initialCategory); setQuery(initialQuery); }, [initialCategory, initialQuery]);
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; ref.current?.querySelector<HTMLInputElement>('input')?.focus(); const handler = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); event.stopPropagation(); close(); } }; document.addEventListener('keydown', handler, true); return () => { document.removeEventListener('keydown', handler, true); previous?.focus(); }; }, [close]);
  const change = (patch: Partial<Settings>) => { void update(patch); };
  const action = async (value: SettingsAction) => { try { const result = await window.markedown.settingsAction(value); if (result.status === 'ok') setMessage(result.value); else if (result.status === 'error' || result.status === 'conflict') error(result.message); } catch (e) { error(String(e)); } };
  const check = (key: BooleanKey, cn: string, en: string, description?: string) => <label className="pref-check"><input type="checkbox" disabled={key === 'diagrams' && !diagramEngineAvailable} checked={key === 'diagrams' && !diagramEngineAvailable ? false : s[key]} onChange={e => change({ [key]: e.target.checked })} /><span>{t(cn,en)}{description && <small>{description}</small>}</span></label>;
  const select = <K extends keyof Settings>(key: K, options: Array<[Settings[K], string]>, label: string) => <select aria-label={label} disabled={key === 'diagramTheme' && !diagramEngineAvailable} value={String(s[key])} onChange={e => change({ [key]: e.target.value })}>{options.map(([value,label]) => <option key={String(value)} value={String(value)}>{label}</option>)}</select>;
  const number = (key: keyof Settings, label: string, min: number, max: number, step = 1) => <CommitInput className="pref-number" label={label} type="number" min={min} max={max} step={step} value={String(s[key])} commit={value => { const parsed = Number(value); if (value.trim() && Number.isFinite(parsed)) change({ [key]: Math.min(max, Math.max(min, Math.round(parsed))) }); }} />;
  const text = (key: keyof Settings, label: string, placeholder?: string) => <CommitInput label={label} value={String(s[key])} placeholder={placeholder} commit={value => change({ [key]: value })} />;
  const button = (cn: string, en: string, onClick: () => void) => <button className="pref-button" type="button" onClick={onClick}>{t(cn,en)}</button>;
  const row = (label: string, control: ReactNode) => <label className="pref-row"><span>{label}</span>{control}</label>;
  interface Group { title: string; hint?: string; keywords?: string; content: ReactNode }
  const categories: Array<[Category,string,string]> = [['file','文件','Files'],['editor','编辑器','Editor'],['image','图像','Images'],['markdown','Markdown','Markdown'],['export','导出','Export'],['appearance','外观','Appearance'],['general','通用','General']];
  const groups: Record<Category, Group[]> = {
    file: [
      { title:t('启动选项','Startup'),content:row(t('启动时','On startup'),select('startup',[['new',t('打开新文件','Open a new file')],['recent',t('打开最近文件','Open recent file')],['workspace',t('打开最近文件夹','Open recent folder')]],t('启动时','On startup'))) },
      { title:t('大纲','Outline'),content:check('outlineCollapsible','允许折叠和展开','Allow folding and expanding') },
      { title:t('默认文件扩展名','Default extension'),content:select('defaultExtension',[['md','.md'],['markdown','.markdown'],['txt','.txt']],t('默认文件扩展名','Default extension')) },
      { title:t('保存与恢复','Save & recovery'),keywords:'自动保存 autosave save drafts 恢复',content:<>{check('autoSave','自动保存','Auto save')}{check('saveOnSwitch','切换文稿时保存原文稿','Save the previous document when switching')}{button('恢复未保存的草稿…','Unsaved drafts…',() => void action('recoveryFolder'))}<p className="pref-hint">{t('未保存草稿会在启动时自动恢复。恢复内容首次写回前需要手动保存。','Unsaved drafts restore on startup and require a manual save before auto saving.')}</p></> },
      { title:t('历史记录','History'),content:<>{check('recordHistory','记录最近使用的文件和文件夹','Record recent files and folders')}{button('清空历史记录','Clear history',() => void action('clearHistory'))}</> },
      { title:t('拖放行为','Drag & drop'),content:<>{row(t('拖入文件夹','Folders'),select('dropFolders',[['open',t('打开文件夹','Open folder')],['ignore',t('忽略','Ignore')]],t('拖入文件夹','Dropped folders')))}{row(t('拖入 Markdown 文件','Markdown files'),select('dropMarkdown',[['open',t('打开文稿','Open document')],['insertLink',t('插入链接','Insert link')]],t('拖入 Markdown 文件','Dropped Markdown')))}{row(t('可导入的文档','Importable documents'),select('dropDocuments',[['import',t('使用 Pandoc 导入','Import with Pandoc')],['ignore',t('忽略','Ignore')]],t('可导入的文档','Importable documents')))}</> },
      { title:t('文件树与文件库','File tree & library'),content:<>{check('showHiddenFiles','显示隐藏文件','Show hidden files')}{row(t('文件类型','File types'),select('fileFilter',[['text',t('Markdown 和文本文件','Markdown and text files')],['markdown',t('仅 Markdown','Markdown only')],['all',t('所有文件','All files')]],t('文件类型','File types')))}</> },
    ],
    editor: [
      { title:t('缩进','Indentation'),content:<>{row(t('缩进宽度','Indent width'),number('indentWidth',t('缩进宽度','Indent width'),1,8))}{check('alignIndent','对齐缩进','Align indentation')}<pre className="indent-preview">{'• '+t('列表','List')+'\n'+' '.repeat(s.indentWidth)+'• '+t('嵌套内容','Nested content')+'\n'+' '.repeat(s.indentWidth*2)+'• '+t('继续书写','Keep writing')}</pre></> },
      { title:t('自动补全','Auto completion'),content:<>{check('pairBrackets','自动配对括号和引号','Auto pair brackets and quotes')}{check('pairMarkdown','自动配对 Markdown 字符','Auto pair Markdown characters')}{check('emojiAutocomplete','Emoji 自动补全','Emoji autocomplete',t('输入 :smile 等名称时显示建议。','Type a name such as :smile to show suggestions.'))}</> },
      { title:t('即时渲染','Live rendering'),content:check('showActiveBlockSource','显示当前编辑块的 Markdown 源码','Show Markdown source in the current block') },
      { title:t('复制与剪切','Copy & cut'),content:<>{check('copyMarkdown','复制纯文本时使用 Markdown 源码','Copy Markdown source as plain text')}{check('copyWholeLine','无选区时复制或剪切整行','Copy or cut the whole line without a selection')}</> },
      { title:t('换行符','Line endings'),hint:t('仅影响新建文件。已有文件保留原始换行格式。','Applies to new files. Existing documents retain their line endings.'),content:select('defaultLineEnding',lineEndingOptions,t('默认换行符','Default line endings')) },
      { title:t('拼写检查','Spellcheck'),content:select('spellcheck',[['auto',t('自动检测语言','Automatic language')],['off',t('关闭','Off')],['en-US','English (US)'],['en-GB','English (UK)']],t('拼写检查','Spellcheck')) },
      { title:t('打字机模式','Typewriter mode'),content:<>{check('alwaysCenterCaret','始终使光标位于编辑区中部','Always center the caret')}{button('退出打字机与专注模式','Exit typewriter and focus modes',disableWritingModes)}</> },
    ],
    image: [
      { title:t('插入图片','Insert images'),hint:t('粘贴、拖入或选择多张图片。未命名文稿先保存，图片按顺序写入文稿旁的目录。','Paste, drop or choose multiple images. Save unnamed documents first; images are stored beside the document in order.'),content:<>{row(t('图片目录','Image folder'),text('imageFolder',t('图片目录','Image folder'),'assets'))}{check('imageUseRelative','优先使用相对路径','Use relative paths')}{check('imageAutoEscape','转义图片路径中的空格和特殊字符','Escape spaces and special characters in image paths')}</> },
      { title:t('显示与性能','Display & performance'),content:<>{check('imageThumbnails','大图使用缓存缩略图','Use cached thumbnails for large images')}<p className="pref-hint">{t('单张图片上限 64 MiB、静态图片上限 2.56 亿像素；动画或多页图片合计上限 8000 万像素、500 帧。每批最多 100 张、合计 256 MiB。','64 MiB and 256 million pixels per static image; animations or multi-page images: 80 million total pixels and 500 frames. Up to 100 images and 256 MiB per batch.')}</p></> },
      { title:t('远程图片','Remote images'),content:<p className="pref-hint">{t('编辑器默认阻止远程图片。HTML 导出可在导出设置中单独允许远程图片。','Remote images are blocked in the editor. They can be allowed separately for HTML exports.')}</p> },
    ],
    markdown: [
      { title:t('Markdown 语法偏好','Markdown syntax'),hint:t('标题、列表样式用于菜单与快捷键生成的内容。','Heading and list styles apply to content created with menus and shortcuts.'),content:<>{check('strictMarkdown','严格模式','Strict mode')}{row(t('标题样式','Headings'),select('headingStyle',[['atx','atx (#)'],['setext','setext (=== / ---)']],t('标题样式','Heading style')))}{row(t('无序列表','Bullet lists'),select('bulletMarker',[['-','-'],['*','*'],['+','+']],t('无序列表标记','Bullet marker')))}{row(t('有序列表','Ordered lists'),select('orderedMarker',[['increment','1. … 2. … 3. …'],['one','1. … 1. … 1. …']],t('有序列表编号','Ordered numbering')))}{row(t('表格样式','Table style'),select('tableStyle',tableStyleNames.map(style => [style, style === 'three-line' ? t('科研三线表（默认）','Scientific three-line (default)') : style === 'grid' ? t('网格表','Grid') : t('简洁横线表','Minimal horizontal rules')]),t('表格样式','Table style')))}</> },
      { title:t('Markdown 扩展语法','Markdown extensions'),content:<>{check('autoLinks','自动识别链接','Automatically detect links')}{check('inlineMath','内联公式　$LaTeX$','Inline math　$LaTeX$')}{check('subscript','下标　H~2~O','Subscript　H~2~O')}{check('superscript','上标　X^2^','Superscript　X^2^')}{check('highlight','高亮　==key==','Highlight　==key==')}{check('githubAlerts','Github 风格警报框','Github style alerts')}{check('diagrams','图表（流程图、序列图与 Mermaid）','Diagrams (flowcharts, sequences and Mermaid)')}{!diagramEngineAvailable && <p className="pref-hint">{t('暂不支持图表预览，图表内容以代码块显示。','Diagram previews are not supported. Diagrams are displayed as code blocks.')}</p>}{row(t('图表主题','Diagram theme'),select('diagramTheme',[['default','Default'],['neutral','Neutral'],['dark','Dark'],['forest','Forest']],t('图表主题','Diagram theme')))}</> },
      { title:t('智能标点','Smart punctuation'),content:<>{select('smartPunctuation',[['off',t('关闭','Off')],['typing',t('输入时转换','Convert while typing')],['render',t('渲染时转换','Convert when rendering')]],t('智能标点','Smart punctuation'))}{check('smartQuotes','智能引号','Smart quotes')}{row(t('双引号','Double quotes'),select('doubleQuoteStyle',[['curly','“abc”'],['guillemet','«abc»']],t('双引号样式','Double quote style')))}{row(t('单引号','Single quotes'),select('singleQuoteStyle',[['curly','‘abc’'],['singleGuillemet','‹abc›']],t('单引号样式','Single quote style')))}{check('smartDashes','智能破折号','Smart dashes')}{check('unicodePunctuation','解析 Markdown 时转换 Unicode 标点','Convert Unicode punctuation when parsing Markdown')}</> },
      { title:t('代码块','Code blocks'),keywords:'代码 缩进 默认语言 自动格式化 code indent language shift tab',content:<>
        {row(t('代码缩进宽度','Code indent width'),number('codeIndentWidth',t('代码缩进宽度','Code indent width'),1,8))}
        {check('codeLineNumbers','显示行号','Show line numbers')}{check('codeWordWrap','代码块自动换行','Wrap code blocks')}
        {check('codeAutoIndent','按 Enter 时自动缩进代码','Auto indent code on Enter')}
        {check('codeAutoIndentOnTab','使用 Shift+Tab 自动调整所选代码缩进','Reindent selected code with Shift+Tab',t('JavaScript、TypeScript、CSS 和 HTML 使用语法缩进；其他语言反缩进一级。只改变选中行的行首空白。','JavaScript, TypeScript, CSS and HTML use syntax indentation; other languages unindent one level. Only leading whitespace on selected lines changes.'))}
        {row(t('默认代码语言','Default code language'),text('defaultCodeLanguage',t('默认代码语言','Default code language'),t('留空或输入 javascript、python…','Leave empty, or enter javascript, python…')))}
        {row(t('自动填写默认语言','Insert default language'),select('codeLanguageTrigger',[['typed',t('输入代码围栏时','When typing a code fence')],['menu',t('使用菜单插入时','When inserting from the menu')],['always',t('输入或菜单插入时','For typing and menu insertion')],['never',t('从不','Never')]],t('默认语言触发方式','Default language trigger')))}
        <p className="pref-hint">{t('输入没有语言标记的代码围栏后按 Enter，或通过菜单新建代码块时生效；已有代码块保持原样。','Applies after Enter on a new fence without a language, or when inserting a code block from the menu. Existing code blocks retain their language.')}</p>
      </> },
      { title:t('数学公式','Math'),keywords:'数学 公式 编号 对齐 位置 alignment number position 复制 SVG MathML LaTeX physics',content:<>
        {button('启用行内公式和公式块','Enable inline math and math blocks',() => change({ inlineMath: true, mathCodeBlocks: true, latexDelimiters: true }))}
        {check('latexDelimiters','支持 LaTeX 公式分隔符 \\(…\\) 和 \\[…\\]','Support LaTeX delimiters \\(…\\) and \\[…\\]')}
        {check('mathCodeBlocks','将 math 代码块渲染为公式','Render math code blocks as equations')}
        {check('mathPhysics','启用 physics 扩展','Enable the physics extension')}
        {check('legacyInlineMath','兼容旧版行内公式解析','Use legacy inline math parsing')}
        {check('mathStandaloneParagraphs','独占段落的行内公式按行间公式处理','Treat standalone body-paragraph math as display equations')}
        {row(t('行间公式自动编号','Display equation numbering'),select('mathNumbering',[['none',t('关闭自动编号','Automatic numbering off')],['labelled',t('仅带标签的公式','Labelled equations only')],['all',t('所有行间公式（默认）','All display equations (default)')]],t('行间公式自动编号','Display equation numbering')))}
        {row(t('公式编号范围','Equation numbering scope'),select('mathNumberingStyle',[['document',t('全文连续编号','Continuous numbering')],['section',t('按一级标题分章编号','Number within level-one headings')]],t('公式编号范围','Equation numbering scope')))}
        {row(t('文档编号形式','Document numbering format'), updateDocumentPrefix ? <CommitInput label={t('编号前缀','Number prefix')} value={documentPrefix || ''} placeholder={t('留空为 1、2…；输入 S 为 S1、S2…','Leave empty for 1, 2…; enter S for S1, S2…')} commit={updateDocumentPrefix} /> : text('mathNumberingPrefix',t('编号前缀','Number prefix'),t('留空为 1、2…；输入 S 为 S1、S2…','Leave empty for 1, 2…; enter S for S1, S2…')))}
        <p className="pref-hint">{t('自动生成的公式编号会加此前缀，适合补充材料使用 S1、S2 等形式；手动 \\tag{…} 编号保持不变。','Automatically generated equation numbers receive this prefix, suitable for supplementary material such as S1, S2; manual \\tag{…} numbers are unchanged.')}</p>
        {row(t('行间公式对齐','Display equation alignment'),select('mathAlignment',[['left',t('左对齐','Left')],['center',t('居中','Center')],['right',t('右对齐','Right')]],t('行间公式对齐','Display equation alignment')))}
        {row(t('编号位置','Number position'),select('mathNumberPosition',[['left',t('左侧','Left')],['right',t('右侧','Right')]],t('编号位置','Number position')))}
        {row(t('公式复制格式','Equation copy format'),select('mathOutput',[['svg','SVG'],['mathml','MathML']],t('公式复制格式','Equation copy format')))}
        <p className="pref-hint">{t('SVG 保留公式外观；MathML 适合支持数学公式编辑的应用。纯文本复制仍可保留 Markdown 源码。','SVG preserves appearance; MathML works with applications that support editable mathematics. Plain-text copies can still retain Markdown source.')}</p>
      </> },
      { title:t('文献引用','Citations'),keywords:'zotero 文献 引用 参考文献 bibliography citation',content:<>
        {row(t('引文样式','Citation style'),select('citationStyle',[['numeric',t('顺序编号','Numeric')],['author-date',t('作者与年份','Author and date')]],t('引文样式','Citation style')))}
        <div className="pref-row"><span>Zotero</span><span>http://localhost:23119/api/</span></div>
        {button('检查 Zotero 连接','Check Zotero connection',()=>void window.markedown.references.status().then(status=>setMessage(status.available?t('Zotero 已连接','Zotero connected')+(status.version?' · '+status.version:''):status.message||t('Zotero 未连接','Zotero disconnected'))).catch(e=>error(String(e))))}
      </> },
      { title:t('段落与空白','Paragraphs & whitespace'),keywords:'段落 空格 换行 首行 缩进 br whitespace linebreak',content:<>
        {check('firstLineIndent','段落首行缩进两个字符','Indent the first line of paragraphs by two characters')}
        {check('showLineBreaks','显示换行标记（<br>）','Show line break markers (<br>)')}
        {row(t('编辑时的空白与换行','Whitespace while editing'),select('editorWhitespace',[['preserve',t('保留空格和换行','Preserve spaces and line breaks')],['breaks',t('保留换行，合并连续空格','Preserve line breaks, collapse spaces')],['collapse',t('合并空格与段内换行','Collapse spaces and soft line breaks')]],t('编辑时的空白与换行','Editor whitespace')))}
        {row(t('导出时的空白与换行','Whitespace when exporting'),select('exportWhitespace',[['preserve',t('保留空格和换行','Preserve spaces and line breaks')],['breaks',t('保留换行，合并连续空格','Preserve line breaks, collapse spaces')],['collapse',t('合并空格与段内换行','Collapse spaces and soft line breaks')]],t('导出时的空白与换行','Export whitespace')))}
        <p className="pref-hint">{t('这些选项控制排版，不改写文稿源码。代码块和公式保留自身的空白规则。','These options affect layout without rewriting Markdown. Code blocks and equations retain their own whitespace rules.')}</p>
      </> },
    ],
    export: [
      { title:t('导出预设','Export presets'),hint:t('选择格式调整选项。预设名称和顺序也用于导出菜单。','Select a format to adjust options. Preset names and order are used in the export dialog.'),content:<div className="export-preferences"><div className="preset-list"><button className={preset === 'general' ? 'selected' : ''} onClick={() => setPreset('general')}>{t('通用','General')}</button>{s.exportPresets.map(entry => <button key={entry.id} className={preset === entry.id ? 'selected' : ''} onClick={() => setPreset(entry.id)}>{entry.name === 'HTML (without styles)' ? t('HTML（无样式）',entry.name) : entry.name === 'Image' ? t('图像','Image') : entry.name}</button>)}<div className="preset-tools"><button title={t('添加预设','Add preset')} aria-label={t('添加预设','Add preset')} onClick={() => { const id = crypto.randomUUID(); change({ exportPresets:[...s.exportPresets,{ id,name:t('新预设','New preset'),format:'html' }] }); setPreset(id); }}><Plus size={15}/></button><button title={t('删除预设','Remove preset')} aria-label={t('删除预设','Remove preset')} disabled={preset === 'general' || s.exportPresets.length < 2} onClick={() => { change({ exportPresets:s.exportPresets.filter(e=>e.id!==preset) }); setPreset('general'); }}><Minus size={15}/></button>{[-1,1].map(direction => <button key={direction} title={t(direction < 0 ? '上移':'下移',direction < 0 ? 'Move up':'Move down')} aria-label={t(direction < 0 ? '上移':'下移',direction < 0 ? 'Move up':'Move down')} disabled={preset==='general' || s.exportPresets.findIndex(e=>e.id===preset)+direction<0 || s.exportPresets.findIndex(e=>e.id===preset)+direction>=s.exportPresets.length} onClick={() => { const next=[...s.exportPresets], i=next.findIndex(e=>e.id===preset); [next[i],next[i+direction]]=[next[i+direction],next[i]]; change({exportPresets:next}); }}>{direction<0?<ArrowUp size={15}/>:<ArrowDown size={15}/>}</button>)}</div></div><div className="preset-options">{preset==='general'?<>
        <h3>{t('通用设置','General settings')}</h3>{row(t('默认导出位置','Default export folder'),<div className="pref-path">{text('exportFolder',t('导出目录','Export folder'),t('自动（文稿目录）','Automatic (document folder)'))}<button title={t('选择导出目录','Choose export folder')} aria-label={t('选择导出目录','Choose export folder')} onClick={() => void window.markedown.chooseExportFolder().then(path=>{if(path)change({exportFolder:path});}).catch(e=>error(String(e)))}><FolderOpen size={17}/></button></div>)}
        {row(t('Pandoc 路径','Pandoc path'),<div className="pref-path">{text('pandocPath',t('Pandoc 路径','Pandoc path'),t('自动检测','Auto detect'))}<button title={t('选择 Pandoc','Choose Pandoc')} aria-label={t('选择 Pandoc','Choose Pandoc')} onClick={() => void window.markedown.choosePandoc().then(path=>{if(path)change({pandocPath:path});}).catch(e=>error(String(e)))}><FolderOpen size={17}/></button></div>)}<p className="pref-hint" title={pandoc||''}>{pandoc===undefined?t('正在检测 Pandoc…','Detecting Pandoc…'):pandoc?t('已找到：','Found: ')+pandoc:t('未找到 Pandoc；HTML、PDF 和图像仍可使用。','Pandoc not found. HTML, PDF and images remain available.')}</p>
        {check('revealAfterExport','导出后显示文件所在目录','Reveal the file after export')}{check('exportTheme','使用当前主题导出','Use the current theme for exports')}{check('exportOutline','包含目录','Include a table of contents')}{button('恢复默认预设','Reset presets',()=>{change({exportPresets:defaultExportPresets});setPreset('general');})}
      </>: (()=>{const entry=s.exportPresets.find(e=>e.id===preset);if(!entry)return null; const edit=(patch:Partial<typeof entry>)=>change({exportPresets:s.exportPresets.map(e=>e.id===preset?{...e,...patch}:e)});return <><h3>{entry.name}</h3>{row(t('预设名称','Preset name'),<CommitInput label={t('预设名称','Preset name')} value={entry.name} commit={name=>edit({name})}/>)}{row(t('格式','Format'),<select value={entry.format} onChange={e=>edit({format:e.target.value as ExportFormat})}>{defaultExportPresets.map(e=><option key={e.id} value={e.format}>{e.name}</option>)}</select>)}{entry.format==='pdf'&&row(t('纸张大小','Paper size'),select('pageSize',[['A4','A4'],['Letter','Letter']],t('纸张大小','Paper size')))}{entry.format==='html'&&check('htmlRemoteImages','允许 HTML 导出引用远程图片','Allow remote images in HTML exports')}{entry.format==='docx'&&<WordPreferences settings={s} zh={zh} change={change}/>}<p className="pref-hint">{['html','htmlPlain','pdf','png'].includes(entry.format)?t('内建导出，包含当前未保存内容。','Built-in export includes current unsaved content.'):t('此格式需要 Pandoc。导出使用当前未保存内容。','This format requires Pandoc and exports current unsaved content.')}</p>{entry.format==='png'&&<p className="pref-hint">{t('长图自动缩放至单边不超过 16,384 像素、总计不超过 4,000 万像素。','Long images scale to at most 16,384 pixels per side and 40 million pixels in total.')}</p>}</>;})()}</div></div> },
    ],
    appearance: [
      { title:t('窗口样式','Window style'),hint:t('关闭全部窗口并重新启动后生效。','Applies after closing all windows and restarting.'),content:select('windowStyle',[['integrated',t('一体化','Integrated')],['classic',t('经典','Classic')]],t('窗口样式','Window style')) },
      { title:t('字号','Font size'),content:<>{select('fontSizeMode',[['auto',t('自动（17 px）','Automatic (17 px)')],['custom',t('自定义','Custom')]],t('字号模式','Font size mode'))}{s.fontSizeMode==='custom'&&row(t('字号','Font size'),number('fontSize',t('字号','Font size'),12,32))}{row(t('阅读宽度','Reading width'),number('readingWidth',t('阅读宽度','Reading width'),480,1400,20))}</> },
      { title:t('缩放','Zoom'),content:<>{row(t('缩放比例','Zoom level'),<div className="pref-inline">{number('zoom',t('缩放比例','Zoom level'),50,200,10)}<span>%</span>{button('重置','Reset',()=>change({zoom:100}))}</div>)}{check('ctrlWheelZoom','按住 Ctrl 并滚动鼠标滚轮缩放','Zoom with Ctrl + mouse wheel')}</> },
      { title:t('状态栏与工具栏','Status & toolbar'),content:<>{check('showStatusBar','显示状态栏','Show status bar')}{row(t('阅读速度（字/分钟）','Reading speed (words/min)'),number('readingSpeed',t('阅读速度','Reading speed'),50,1000))}{check('showToolbar','显示编辑器工具栏','Show editor toolbar')}</> },
      { title:t('主题','Themes'),content:<>{select('theme',themeNames.map(name=>[name,themeLabels[name]]),t('主题','Theme'))}{check('separateDarkTheme','为系统深色模式使用独立主题','Use a separate theme in system dark mode')}{s.separateDarkTheme&&row(t('深色主题','Dark theme'),select('darkTheme',themeNames.map(name=>[name,themeLabels[name]]),t('深色主题','Dark theme')))}{button('打开主题说明文件夹','Open theme information folder',()=>void action('themeFolder'))}<p className="pref-hint">{t('提供五种内建主题，暂不支持安装外部主题。','Choose from five built-in themes. Installing external themes is not supported.')}</p></> },
    ],
    general: [
      { title:t('语言','Language'),content:select('language',[['system',t('系统语言','System language')],['zh-CN','简体中文'],['en','English']],t('语言','Language')) },
      { title:t('更新','Updates'),content:<p className="pref-hint">{t('安装新版 Markedown 即可升级，文稿和设置会保留。暂不支持自动更新。','Install a newer version of Markedown to upgrade. Your documents and settings are retained. Automatic updates are not supported.')}</p> },
      { title:'Markedown',content:<><p className="pref-version">Markedown {version} · {platformName} {arch}</p>{button('打开应用数据目录','Open app data folder',()=>void action('dataFolder'))}<CitationCredits /></> },
      { title:t('快捷键','Keyboard shortcuts'),content:<>{button(shortcuts?'收起自定义快捷键':'自定义快捷键…',shortcuts?'Hide shortcuts':'Customize shortcuts…',()=>setShortcuts(!shortcuts))}{shortcuts&&<div className="shortcut-list">{shortcutCommands.map(([command,cn,en,fallback])=>row(t(cn,en),<input key={command} aria-label={t(cn,en)+t('快捷键',' shortcut')} value={s.shortcuts[command]||fallback} readOnly onKeyDown={e=>{e.preventDefault();e.stopPropagation(); if(['Control','Shift','Alt','Meta'].includes(e.key))return;if(e.key==='Backspace'||e.key==='Delete'){const next={...s.shortcuts};delete next[command];change({shortcuts:next});return;}if(!e.ctrlKey&&!e.altKey&&!/^F(?:[1-9]|1[0-2])$/.test(e.key)){setMessage(t('请使用 Ctrl、Alt 或功能键组合。','Use Ctrl, Alt or a function key.'));return;}const key=[e.ctrlKey?'Ctrl':'',e.altKey?'Alt':'',e.shiftKey?'Shift':'',e.key.length===1?e.key.toUpperCase():e.key].filter(Boolean).join('+');const used=shortcutCommands.find(([id,,,base])=>id!==command&&(s.shortcuts[id]||base).toLowerCase()===key.toLowerCase());if(used){setMessage(t('此快捷键已被使用。','This shortcut is already in use.'));return;}change({shortcuts:{...s.shortcuts,[command]:key}});}}/>))}<small>{t('点选输入框并按下组合键；Backspace 恢复默认。','Focus a field and press a shortcut; Backspace restores its default.')}</small></div>}</> },
      ...(platform === 'win32' ? [{ title:t('Windows 集成','Windows integration'),content:<div className="pref-buttons">{button('在资源管理器“新建”中添加 Markdown','Add Markdown to Explorer New menu',()=>void action('registerNewFile'))}{button('移除“新建 Markdown”','Remove Markdown from New menu',()=>void action('unregisterNewFile'))}</div> }] : []),
      { title:t('高级设置','Advanced'),content:<><div className="pref-buttons">{button('开发者工具','Developer tools',()=>void action('debug'))}{button('打开高级设置文件','Open advanced settings',()=>void action('advancedSettings'))}{button('恢复默认设置','Restore defaults',()=>void action('resetSettings'))}</div><p className="pref-hint">{t('恢复默认设置不会删除文稿。','Restoring default settings does not delete your documents.')}</p></> },
    ],
  };
  const needle=query.trim().toLowerCase();
  const matches=(group:Group)=>!needle||(group.title+' '+(group.keywords||'')+' '+flattenText(group.content)+' '+(group.hint||'')).toLowerCase().includes(needle);
  const visible=needle?categories.filter(([id])=>groups[id].some(matches)):categories.filter(([id])=>id===category);
  return <section className="preferences-page" ref={ref} role="dialog" aria-label={t('偏好设置','Preferences')} aria-modal="true" data-testid="preferences"><header className="preferences-header"><span>{t('偏好设置','Preferences')}</span><button aria-label={t('关闭偏好设置','Close preferences')} title={t('关闭','Close')} onClick={close}><X size={22}/></button></header><div className="preferences-body"><aside className="preferences-nav"><div className="pref-search"><Search size={15}/><input placeholder={t('查找…','Search…')} aria-label={t('搜索设置','Search settings')} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label={t('清空搜索','Clear search')} onClick={()=>setQuery('')}><X size={14}/></button>}</div><nav>{categories.map(([id,cn,en])=><button key={id} aria-current={!needle&&category===id?'page':undefined} className={!needle&&category===id?'selected':''} onClick={()=>{setCategory(id);setQuery('');setMessage('');ref.current?.querySelector('.preferences-content')?.scrollTo(0,0);}}>{t(cn,en)}</button>)}</nav><small>Markedown {version}</small></aside><div className="preferences-content">{visible.length?visible.map(([id,cn,en])=><div className={`preference-category category-${id}`} key={id}><h1>{t(cn,en)}</h1>{groups[id].filter(matches).map(group=><section className="pref-group" key={group.title}><div className="pref-group-label"><h2>{group.title}</h2>{group.hint&&<p>{group.hint}</p>}</div><div className="pref-controls">{group.content}</div></section>)}</div>):<div className="pref-empty">{t('没有匹配的设置','No matching settings')}</div>}{message&&<div className="pref-message" role="status">{message}<button aria-label={t('关闭提示','Dismiss')} onClick={()=>setMessage('')}><X size={15}/></button></div>}</div></div></section>;
}
function flattenText(node: ReactNode): string { if(typeof node==='string'||typeof node==='number')return String(node);if(Array.isArray(node))return node.map(flattenText).join(' ');if(node&&typeof node==='object'&&'props'in node){const props=node.props as {children?:ReactNode;'aria-label'?:string;title?:string};return [props['aria-label'],props.title,flattenText(props.children)].join(' ');}return ''; }

function CommitInput({value,commit,label,...props}:{value:string;commit(value:string):void;label:string;className?:string;placeholder?:string;type?:string;min?:number;max?:number;step?:number}) { const [draft,setDraft]=useState(value); const focused=useRef(false); useEffect(()=>{if(!focused.current)setDraft(value);},[value]); return <input {...props} aria-label={label} value={draft} onFocus={()=>{focused.current=true;}} onChange={event=>setDraft(event.target.value)} onBlur={()=>{focused.current=false;if(draft!==value)commit(draft);}} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();event.currentTarget.blur();}}}/>; }
